export const ACTIONS = {
  FETCH_COMPANIES_INIT: "FETCH_COMPANIES_INIT",
  FETCH_COMPANIES_SUCCEDED: "FETCH_COMPANIES_SUCCEDED",
  FETCH_COMPANIES_FAILED: "FETCH_COMPANIES_FAILED",

  CLEAR_COMPANY_FORM: "CLEAR_COMPANY_FORM",

  CREATE_COMPANY_INIT: "CREATE_COMPANY_INIT",
  CREATE_COMPANY_SUCCEDED: "CREATE_COMPANY_SUCCEDED",
  CREATE_COMPANY_FAILED: "CREATE_COMPANY_FAILED",

  FETCH_COMPANY_INIT: "FETCH_COMPANY_INIT",
  FETCH_COMPANY_SUCCEDED: "FETCH_COMPANY_SUCCEDED",
  FETCH_COMPANY_FAILED: "FETCH_COMPANY_FAILED",

  EDIT_COMPANY_INIT: "EDIT_COMPANY_INIT",
  EDIT_COMPANY_SUCCEDED: "EDIT_COMPANY_SUCCEDED",
  EDIT_COMPANY_FAILED: "EDIT_COMPANY_FAILED",

  DELETE_COMPANY_INIT: "DELETE_COMPANY_INIT",
  DELETE_COMPANY_SUCCEDED: "DELETE_COMPANY_SUCCEDED",
  DELETE_COMPANY_FAILED: "DELETE_COMPANY_FAILED",

  FILTER_COMPANIES: "FILTER_COMPANIES"
}

export const ENDPOINT = {
  COMPANIES: "/api/companies",
  COMPANY: "/api/company/:param"
}
