version: '2'

services:
  survey_build:
    image: predictanalyse/survey-front:latest
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    env_file:
      - ./.env
