export const ACTIONS = {
  FETCH_MANAGER_INVITATIONS_INIT: "FETCH_MANAGER_INVITATIONS_INIT",
  FETCH_MANAGER_INVITATIONS_SUCCEDED: "FETCH_MANAGER_INVITATIONS_SUCCEDED",
  FETCH_MANAGER_INVITATIONS_FAILED: "FETCH_MANAGER_INVITATIONS_FAILED",

  FETCH_ALL_COMPANIES_INIT: "FETCH_ALL_COMPANIES_INIT",
  FETCH_ALL_COMPANIES_SUCCEDED: "FETCH_ALL_COMPANIES_SUCCEDED",
  FETCH_ALL_COMPANIES_FAILED: "FETCH_ALL_COMPANIES_FAILED",

  CLEAR_MANAGER_INVITATION_FORM: "CLEAR_MANAGER_INVITATION_FORM",

  CREATE_MANAGER_INVITATION_INIT: "CREATE_MANAGER_INVITATION_INIT",
  CREATE_MANAGER_INVITATION_SUCCEDED: "CREATE_MANAGER_INVITATION_SUCCEDED",
  CREATE_MANAGER_INVITATION_FAILED: "CREATE_MANAGER_INVITATION_FAILED",

  FETCH_MANAGER_INVITATION_INIT: "FETCH_MANAGER_INVITATION_INIT",
  FETCH_MANAGER_INVITATION_SUCCEDED: "FETCH_MANAGER_INVITATION_SUCCEDED",
  FETCH_MANAGER_INVITATION_FAILED: "FETCH_MANAGER_INVITATION_FAILED",

  EDIT_MANAGER_INVITATION_INIT: "EDIT_MANAGER_INVITATION_INIT",
  EDIT_MANAGER_INVITATION_SUCCEDED: "EDIT_MANAGER_INVITATION_SUCCEDED",
  EDIT_MANAGER_INVITATION_FAILED: "EDIT_MANAGER_INVITATION_FAILED",

  DELETE_MANAGER_INVITATION_INIT: "DELETE_MANAGER_INVITATION_INIT",
  DELETE_MANAGER_INVITATION_SUCCEDED: "DELETE_MANAGER_INVITATION_SUCCEDED",
  DELETE_MANAGER_INVITATION_FAILED: "DELETE_MANAGER_INVITATION_FAILED",

  FILTER_MANAGER_INVITATIONS: "FILTER_MANAGER_INVITATIONS"
}

export const ENDPOINT = {
  ALL_COMPANIES: "/api/all/companies",
  MANAGER_INVITATIONS: "/api/invitations/manager",
  MANAGER_INVITATION: "/api/invitation/manager/:param"
}
