export const API_BASE_URL = window._ENV_.REACT_APP_API_BASE_URL
export const SENTRY_DSN = window._ENV_.REACT_APP_SENTRY_DSN
export const API_QUESTION_BASE_URL = window._ENV_.REACT_APP_API_QUESTION_BASE_URL
export const API_FOOD_BASE_URL = window._ENV_.REACT_APP_API_FOOD_BASE_URL

