export const ACTIONS = {
  FETCH_COMPANY_INVITATIONS_INIT: "FETCH_COMPANY_INVITATIONS_INIT",
  FETCH_COMPANY_INVITATIONS_SUCCEDED: "FETCH_COMPANY_INVITATIONS_SUCCEDED",
  FETCH_COMPANY_INVITATIONS_FAILED: "FETCH_COMPANY_INVITATIONS_FAILED",

  CLEAR_COMPANY_INVITATION_FORM: "CLEAR_COMPANY_INVITATION_FORM",

  CREATE_COMPANY_INVITATION_INIT: "CREATE_COMPANY_INVITATION_INIT",
  CREATE_COMPANY_INVITATION_SUCCEDED: "CREATE_COMPANY_INVITATION_SUCCEDED",
  CREATE_COMPANY_INVITATION_FAILED: "CREATE_COMPANY_INVITATION_FAILED",

  SEND_COMPANY_INVITATION_INIT: "SEND_COMPANY_INVITATION_INIT",
  SEND_COMPANY_INVITATION_SUCCEDED: "SEND_COMPANY_INVITATION_SUCCEDED",
  SEND_COMPANY_INVITATION_FAILED: "SEND_COMPANY_INVITATION_FAILED",

  FETCH_COMPANY_INVITATION_INIT: "FETCH_COMPANY_INVITATION_INIT",
  FETCH_COMPANY_INVITATION_SUCCEDED: "FETCH_COMPANY_INVITATION_SUCCEDED",
  FETCH_COMPANY_INVITATION_FAILED: "FETCH_COMPANY_INVITATION_FAILED",

  EDIT_COMPANY_INVITATION_INIT: "EDIT_COMPANY_INVITATION_INIT",
  EDIT_COMPANY_INVITATION_SUCCEDED: "EDIT_COMPANY_INVITATION_SUCCEDED",
  EDIT_COMPANY_INVITATION_FAILED: "EDIT_COMPANY_INVITATION_FAILED",

  DELETE_COMPANY_INVITATION_INIT: "DELETE_COMPANY_INVITATION_INIT",
  DELETE_COMPANY_INVITATION_SUCCEDED: "DELETE_COMPANY_INVITATION_SUCCEDED",
  DELETE_COMPANY_INVITATION_FAILED: "DELETE_COMPANY_INVITATION_FAILED",

  FILTER_COMPANY_INVITATIONS: "FILTER_COMPANY_INVITATIONS"
}

export const ENDPOINT = {
  COMPANY_INVITATIONS: "/api/invitations/company",
  COMPANY_INVITATION: "/api/invitation/company/:param",
  SEND_COMPANY_INVITATION: "/api/invitation/company/:param",
}
